# global settings
[build]
  command = "npm run build"
  publish = "dist"

# target builds from master branch
[context.production.environment]
  # prevent installation of devDependencies
  NODE_ENV = "production"

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    cache-control = "max-age=0,no-cache,no-store,must-revalidate,X-Custom-Header=foo"
