# global settings
[build]
  command = "npm run build"
  publish = "dist"

# target builds from master branch
[context.production.environment]
  # prevent installation of devDependencies
  NODE_ENV = "production"

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    cache-control = "max-age=0,no-cache,no-store,must-revalidate"
    x-custom-header = "foo"

[[headers]]
  for = "/*"
  [headers.values]
    x-other-header = "bar"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true # COMMENT: ensure that we always redirect
